apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: larrya/client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: larrya/comments
      context: comments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: larrya/posts
      context: posts
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: larrya/events
      context: events
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: larrya/query
      context: query
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: larrya/moderation
      context: moderation
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .